Add mypy dependency to build requirements in meta.yaml
tudat-team/tudatpy-feedstock pull request #15
Opened 2024-06-25 17:03 UTC by alopezrivera

2024-06-28 11:47 UTC, DominicDirkx commented on recipe/build.sh
> +conda install numpy scipy matplotlib tqdm -y
Hi @alopezrivera I don't think this should be added here, but rather in the recipe.yamp, to ensure consistency

2024-06-28 12:00 UTC, DominicDirkx commented on recipe/meta.yaml
> +  {% set git_rev = "c51a1b5490df82bec17c3a12108c3f304412a539" %}
Why this specific commit?

2024-06-28 12:09 UTC, DominicDirkx commented on recipe/build.sh
> +conda install numpy scipy matplotlib tqdm -y
Great to hear from you! Where did you push the changes?

2024-06-28 12:12 UTC, DominicDirkx commented on recipe/build.sh
> +conda install numpy scipy matplotlib tqdm -y
Great to hear from you! And thanks :)

2024-06-28 12:16 UTC, DominicDirkx commented on recipe/meta.yaml
> +  {% set git_rev = "c51a1b5490df82bec17c3a12108c3f304412a539" %}
I had a look and this was a very old version, which may explain some of the compilation errors. I've updated it

2024-06-28 13:34 UTC, geoffreygarrett requested changes

2024-06-28 13:34 UTC, geoffreygarrett commented on recipe/meta.yaml
> +  {% set git_rev = "0.8.0.dev9" %}
Looks to be an incorrect tag?

2024-06-28 13:42 UTC, geoffreygarrett approved these changes

2024-07-01 18:52 UTC, DominicDirkx commented
Hi all, this issue started with the release of v0.8.0.dev9, which caused a whole bunch of issues in the tudatpy build that seem difficult to resolve. I've rolled back the release, and have re-opened the pull request:

https://github.com/tudat-team/tudatpy/pull/154

before merging this, I propose we fix the Azure build of the associated changes, by hard-coding the commit in the recipe.yaml, rather than assigning a version. That way, we can merge other tudatpy features, while we resolve this one on the side. I'll patch up the develop branch of the feedstock.

2024-07-11 21:49 UTC, geoffreygarrett commented
AFAK https://github.com/sizmailov/pybind11-stubgen would be the way to go if mypy was intended for stub generation for code completion etc. I've used it successfully in the past.

2024-07-11 21:51 UTC, geoffreygarrett commented
I'll close this for now

2024-07-11 21:51 UTC, closed without merging